services:
  telegram-reaction:
    build: .
    container_name: telegram-reaction
    volumes:
      - ./session:/app/session
      - ./logs:/app/logs
    environment:
      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}
      - TG_CHANNELS=${TG_CHANNELS}
      - TG_REACTION=${TG_REACTION}
    stdin_open: true
    tty: true
